apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dkekcns3r-python
  janus-idp.io/tekton: dkekcns3r-python
  backstage.io/kubernetes-id: dkekcns3r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dkekcns3r-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
